apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  namespace: ai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gautamsahil/ai-task-worker:20d593e65f5c017e96883f526d4d1c06057bfdd5
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: platform-config
        resources:
          requests:
            memory: "256Mi" # Increased
            cpu: "100m"
          limits:
            memory: "512Mi" # Increased
            cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  namespace: ai-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70